/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : IDL.Nat,
  'isPresent' : IDL.Bool,
  'date' : IDL.Text,
  'subjectId' : IDL.Nat,
});
export const AttendanceSummary = IDL.Record({
  'studentId' : IDL.Nat,
  'presentCount' : IDL.Nat,
  'subjectId' : IDL.Nat,
  'totalSessions' : IDL.Nat,
});
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'principal' : IDL.Opt(IDL.Principal),
  'semester' : IDL.Nat,
  'name' : IDL.Text,
  'section' : IDL.Text,
  'email' : IDL.Text,
  'enrollmentNumber' : IDL.Text,
});
export const Subject = IDL.Record({
  'id' : IDL.Nat,
  'semester' : IDL.Nat,
  'code' : IDL.Text,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStudent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteStudent' : IDL.Func([IDL.Nat], [], []),
  'deleteSubject' : IDL.Func([IDL.Nat], [], []),
  'getAttendanceByStudent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceBySubject' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceSummary' : IDL.Func(
      [],
      [IDL.Vec(AttendanceSummary)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyAttendanceSummary' : IDL.Func(
      [],
      [IDL.Vec(AttendanceSummary)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'listSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'markAttendance' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Bool))],
      [],
      [],
    ),
  'registerPrincipal' : IDL.Func([IDL.Text], [], []),
  'updateStudent' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateSubject' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : IDL.Nat,
    'isPresent' : IDL.Bool,
    'date' : IDL.Text,
    'subjectId' : IDL.Nat,
  });
  const AttendanceSummary = IDL.Record({
    'studentId' : IDL.Nat,
    'presentCount' : IDL.Nat,
    'subjectId' : IDL.Nat,
    'totalSessions' : IDL.Nat,
  });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'principal' : IDL.Opt(IDL.Principal),
    'semester' : IDL.Nat,
    'name' : IDL.Text,
    'section' : IDL.Text,
    'email' : IDL.Text,
    'enrollmentNumber' : IDL.Text,
  });
  const Subject = IDL.Record({
    'id' : IDL.Nat,
    'semester' : IDL.Nat,
    'code' : IDL.Text,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStudent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteStudent' : IDL.Func([IDL.Nat], [], []),
    'deleteSubject' : IDL.Func([IDL.Nat], [], []),
    'getAttendanceByStudent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceBySubject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceSummary' : IDL.Func(
        [],
        [IDL.Vec(AttendanceSummary)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyAttendanceSummary' : IDL.Func(
        [],
        [IDL.Vec(AttendanceSummary)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'listSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'markAttendance' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Bool))],
        [],
        [],
      ),
    'registerPrincipal' : IDL.Func([IDL.Text], [], []),
    'updateStudent' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateSubject' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };