/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'id' : bigint,
  'studentId' : bigint,
  'isPresent' : boolean,
  'date' : string,
  'subjectId' : bigint,
}
export interface AttendanceSummary {
  'studentId' : bigint,
  'presentCount' : bigint,
  'subjectId' : bigint,
  'totalSessions' : bigint,
}
export interface Student {
  'id' : bigint,
  'principal' : [] | [Principal],
  'semester' : bigint,
  'name' : string,
  'section' : string,
  'email' : string,
  'enrollmentNumber' : string,
}
export interface Subject {
  'id' : bigint,
  'semester' : bigint,
  'code' : string,
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStudent' : ActorMethod<[string, string, bigint, string, string], bigint>,
  'addSubject' : ActorMethod<[string, string, bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteStudent' : ActorMethod<[bigint], undefined>,
  'deleteSubject' : ActorMethod<[bigint], undefined>,
  'getAttendanceByStudent' : ActorMethod<[bigint], Array<AttendanceRecord>>,
  'getAttendanceBySubject' : ActorMethod<[bigint], Array<AttendanceRecord>>,
  'getAttendanceSummary' : ActorMethod<[], Array<AttendanceSummary>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyAttendanceSummary' : ActorMethod<[], Array<AttendanceSummary>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listStudents' : ActorMethod<[], Array<Student>>,
  'listSubjects' : ActorMethod<[], Array<Subject>>,
  'markAttendance' : ActorMethod<
    [bigint, string, Array<[bigint, boolean]>],
    undefined
  >,
  'registerPrincipal' : ActorMethod<[string], undefined>,
  'updateStudent' : ActorMethod<
    [bigint, string, string, bigint, string, string],
    undefined
  >,
  'updateSubject' : ActorMethod<[bigint, string, string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];